import type { Metadata } from 'next';
import './globals.css';
import { IranYekanX } from '../definitions/fonts';
import { ConfigProvider } from 'antd';
import faIR from 'antd/locale/fa_IR';
import Header from './_components/header/header';
import style from './layout.module.scss';
import 'react-toastify/dist/ReactToastify.css';
export const metadata: Metadata = {
  title: 'پشتیبانی سیستم‌های جریان ضعیف شهرک چیتگر',
  // description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={IranYekanX.variable}>
      <ConfigProvider direction="rtl" locale={faIR}>
        <body>
          <div className={`${style.container}`}>{children}</div>
        </body>
      </ConfigProvider>
    </html>
  );
}
