import type { Metadata } from 'next';
import './globals.scss';
import { IranYekanX } from '../definitions/fonts';
import { ConfigProvider } from 'antd';
import faIR from 'antd/locale/fa_IR';

import 'react-toastify/dist/ReactToastify.css';
import BottomNav from './_components/bottomNav/BottomNav';
import { ErrorProvider } from '@/lib/hook/errorContext';
export const metadata: Metadata = {
  title: 'پشتیبانی سیستم‌های جریان ضعیف شهرک چیتگر',
  // description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const { isMobile, isDesktop, isTablet } = useResponsive();
  return (
    <html lang="fa" dir="rtl" className={IranYekanX.variable}>
      <ErrorProvider>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: '#0098a9',
              borderRadius: 4,
              fontFamily: IranYekanX.style.fontFamily,
            },
          }}
          direction="rtl"
          locale={faIR}
        >
          <body>
            <div>{children}</div>
            <BottomNav />
          </body>
        </ConfigProvider>
      </ErrorProvider>
    </html>
  );
}
