import type { Metadata } from 'next';
import './globals.css';
import { IranYekanX } from '../definitions/fonts';
import { ConfigProvider } from 'antd';
import faIR from 'antd/locale/fa_IR';

import 'react-toastify/dist/ReactToastify.css';
export const metadata: Metadata = {
  title: 'پشتیبانی سیستم‌های جریان ضعیف شهرک چیتگر',
  // description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={IranYekanX.variable}>
      <ConfigProvider
        theme={{
          token: {
            colorPrimary: '#0098a9',
            borderRadius: 4,
            fontFamily: IranYekanX.style.fontFamily,
          },
        }}
        direction="rtl"
        locale={faIR}
      >
        <body>
          <div>{children}</div>
        </body>
      </ConfigProvider>
    </html>
  );
}
