name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[no-pipeline]')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        run: |
          docker build -t sepehrrajabi/helpdesk-frontend:latest -t avijeh_iptv:$(date +%s) .
          docker push sepehrrajabi/helpdesk-frontend:latest